# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('1', 'Policial'), ('2', 'Politica'), ('3', 'Cultura'), ('4', 'Esporte')], default='SOME STRING', max_length=1),
        ),
    ]
