# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0002_post_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('policial', 'Policial'), ('politica', 'Politica'), ('cultura', 'Cultura'), ('esporte', 'Esporte')], default='SOME STRING', max_length=10),
        ),
    ]
