# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0005_loteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Megasena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurso_loteria', models.CharField(max_length=50)),
                ('data_loteria', models.CharField(max_length=50)),
                ('acerto_loteria', models.CharField(max_length=50)),
                ('entrada_usuario', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=200)),
            ],
        ),
    ]
