# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0006_megasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=150)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='')),
                ('data', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
