# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0007_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='fone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='descricao',
            field=models.TextField(),
        ),
    ]
