# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0008_auto_20170531_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='fone',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='contato',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
