# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0009_auto_20170602_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comentario',
        ),
    ]
