# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0010_remove_post_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagem_1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
