# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0012_auto_20170609_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagem_produto_1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='imagem_produto_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='imagem_produto_3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
