# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0013_auto_20170613_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagem_produto_4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='imagem_produto_5',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
