# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0014_auto_20170613_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio_imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='files/%Y/%m/%d')),
                ('Anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncio', to='radiosite.Anuncio')),
            ],
        ),
    ]
