# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0015_anuncio_imagens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio_imagens',
            old_name='Anuncio',
            new_name='anuncio',
        ),
    ]
