# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0016_auto_20170613_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='imagem_1',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='imagem_produto_1',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='imagem_produto_2',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='imagem_produto_3',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='imagem_produto_4',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='imagem_produto_5',
        ),
        migrations.RemoveField(
            model_name='anuncio_imagens',
            name='anuncio',
        ),
    ]
