# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0018_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiosite.Anuncio', verbose_name='Anuncio'),
        ),
    ]
