# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0020_auto_20170620_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiosite.Anuncio')),
            ],
        ),
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='radiosite.Anuncio', verbose_name='Anuncio'),
        ),
    ]
