# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiosite', '0021_auto_20170703_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cont',
            field=models.IntegerField(null=True),
        ),
    ]
